apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argo-test-omgeving
    namespace: test
spec:
    project: default
    source:
        path: helm
        repoURL: https://github.com/ChampiYann/argo-test-omgeving
        targetRevision: HEAD
    destination:
        namespace: test
        server: https://kubernetes.default.svc