apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mule-hello-world
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: 'http://172.17.0.2:8080'
        targetRevision: 1.0.8
        chart: helloworld
        helm:
            values: |
                replicaCount: {{ .Values.replicaCount }}
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
    syncPolicy:
        automated:
            selfHeal: true
            prune: true