apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mule-hello-world
    namespace: argocd
spec:
    project: default
    source:
        repoURL: 'http://172.17.0.2:8080'
        targetRevision: 1.0.1
        chart: helloworld
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
    syncPolicy: {}