apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mule-hello-world
    namespace: test
spec:
    project: default
    source:
        chart: helloworld
        repoURL: http://172.17.0.2:8080
        targetRevision: 1.0.0
    destination:
        namespace: test
        server: https://kubernetes.default.svc