apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: spring-boot-app
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: 'http://172.17.0.2:8080'
        targetRevision: 0.1.0
        chart: springboot
        helm:
            values: |
                replicaCount: 2
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
    syncPolicy:
        automated:
            selfHeal: true
            prune: true